name: code-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - run: make install
      - run: make lint
      - name: Test
        run: make test
        env:
          SESSION_KEY: ${{ secrets.SESSION_KEY }}
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v5.0.0
        # Add Code Climate secret key
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          SESSION_KEY: ${{ secrets.SESSION_KEY }}
        with:
          coverageCommand: make test-coverage
          debug: true
